In [1]:
import duckdb

con = duckdb.connect()

amazon = con.execute("""
    SELECT *
    FROM read_parquet(
        '../data/processed/amazon_conversations.parquet'
    )
""").df()

amazon.shape

(373312, 7)

In [2]:
amazon.head(20)

,conversation_id,depth,tweet_id,author_id,role,created_at,text
0,1000119,0,1000119,356779,customer,2017-10-22 22:51:06+05:30,Irritated on principle. I spent 2+ hrs looking...
1,1000119,1,1000117,AmazonHelp,support,2017-10-22 22:57:10+05:30,@356779 I'm sorry for the poor experience! Whe...
2,1000119,2,1000118,356779,customer,2017-10-22 23:15:55+05:30,@AmazonHelp It's all good now 😊 I chatted in &...
3,1000119,3,1000120,AmazonHelp,support,2017-10-22 23:22:00+05:30,@356779 Thanks for letting us know! We're alwa...
4,1000119,4,1000121,356779,customer,2017-10-22 23:26:09+05:30,@AmazonHelp https://t.co/q3YI6TgBjO
5,1000123,0,1000123,356780,customer,2017-10-22 22:51:46+05:30,@115830 I just inadvertently bought a Kindle b...
6,1000123,1,1000122,AmazonHelp,support,2017-10-22 22:57:00+05:30,@356780 Oh no! Please give us a call here: htt...
7,1000125,0,1000125,356781,customer,2017-10-22 22:46:40+05:30,@119625 Please upload south movies in hindi audio
8,1000125,1,1000124,AmazonHelp,support,2017-10-22 22:56:41+05:30,"@356781 I understand your concern, Nehal. I'll..."
9,1000127,0,1000127,356782,customer,2017-10-22 22:48:55+05:30,@43895 watching Loveless on Amazon prime cuz o...
10,1000127,1,1000126,AmazonHelp,support,2017-10-22 22:54:29+05:30,@356782 I'm sorry for the subtitle issues. Ple...
11,1000130,0,1000130,356783,customer,2017-10-22 22:32:23+05:30,@117093 sign up page appears broken. Cannot si...
12,1000130,1,1000128,AmazonHelp,support,2017-10-22 22:53:30+05:30,@356783 Oh no! That's not supposed to happen. ...
13,1000130,2,1000129,356783,customer,2017-10-23 02:56:29+05:30,"@AmazonHelp For a while, every time I tried to..."
14,1000133,0,1000133,356784,customer,2017-10-22 22:30:15+05:30,Amazon now sell duplicate product. I bought Bi...
15,1000133,1,1000131,AmazonHelp,support,2017-10-22 22:53:00+05:30,@356784 Sorry for the trouble with your order....
16,1000133,2,1000132,356784,customer,2017-10-23 00:42:01+05:30,@AmazonHelp Order ID: 404-0496716-8940319\nPeo...
17,1000133,3,1000135,AmazonHelp,support,2017-10-23 00:53:56+05:30,"@356784 I understand your concern, Prasid. Pl..."
18,1000133,4,1000138,356784,customer,2017-10-23 00:56:08+05:30,@AmazonHelp I already connected. Did live chat...
19,1000133,3,1000134,AmazonHelp,support,2017-10-23 00:57:31+05:30,"@356784 Please don't provide your details, we ..."

In [3]:
amazon["role"].value_counts()

role
customer    202994
support     170318
Name: count, dtype: int64

In [4]:
customer_messages = amazon[
    amazon["role"] == "customer"
].copy()

print("Customer messages:", len(customer_messages))

Customer messages: 202994

In [5]:
customer_messages[
    ["conversation_id", "created_at", "text"]
].sample(
    50,
    random_state=42
)

,conversation_id,created_at,text
187538,2526960,2017-11-16 09:56:22+05:30,@115821 I ordered a popsocket for my sons 13th...
277074,395980,2017-10-10 00:32:20+05:30,@AmazonHelp Ok gracias otra vez!
283104,42576,2017-11-01 21:14:27+05:30,@115850 when you say cash on delivery is it ho...
77390,151988,2017-11-24 21:30:58+05:30,@AmazonHelp https://t.co/N8MVG9Zfyb
289581,453361,2017-12-01 04:02:47+05:30,@AmazonHelp Heyyy @AmazonHelp 😰
260903,321194,2017-10-07 19:05:09+05:30,@AmazonHelp Can’t. On my way to catch a flight...
97258,1672266,2017-11-06 13:50:13+05:30,Amazonで注文してたウルトラカプセルが届いたぜ。 https://t.co/iVaJME...
28099,1207990,2017-10-25 15:34:18+05:30,"@AmazonHelp Thanks for quick response, I will"
256294,302253,2017-10-07 03:29:38+05:30,"@AmazonHelp 2/2 That is extremely problematic,..."
17232,1124530,2017-10-24 14:50:51+05:30,@AmazonHelp Amazon mailed me on 7th august tha...
29187,1212226,2017-10-25 18:08:35+05:30,who do i talk to about a product being wrong i...
267245,350633,2017-10-08 15:47:14+05:30,"Bonjour @120533, je ne sais toujours pas la fi..."
368502,974935,2017-10-14 12:24:43+05:30,"Hallo @116316, wann lernt @115833 mehr als ein..."
29095,1211671,2017-10-26 15:22:07+05:30,@AmazonHelp Ok. But how will i be sure enough ...
322831,669168,2017-11-23 10:02:55+05:30,Someone stole all my packages from my porch to...
240724,2895965,2017-11-28 21:52:36+05:30,Os livros que eu comprei na @117086 na Black F...
80551,1547893,2017-11-04 14:25:24+05:30,@AmazonHelp If I buy it on the high st can I s...
230353,2837013,2017-11-27 20:29:43+05:30,"@AmazonHelp Maybe your delivery guys could, sa..."
192521,2558564,2017-11-16 22:26:04+05:30,@AmazonHelp Emails phone calls and NO SATISFAC...
307790,558397,2017-12-03 03:28:12+05:30,@AmazonHelp I would like to get the police inv...
106304,1738404,2017-11-07 15:52:48+05:30,@116928 que fácil es suscribirte a Unlimited ...
33791,1243364,2017-10-26 04:50:44+05:30,@AmazonHelp I submitted and sent in my Kindle ...
219295,2771674,2017-11-21 19:28:01+05:30,@AmazonHelp Have sent you a message!
111604,1779353,2017-10-23 18:46:25+05:30,@115850 need help 😡 fake e commerce site 😡
280126,418134,2017-10-03 21:48:12+05:30,"@116875 Pues a pesar de lo tardado que fue, a..."
160551,2320278,2017-11-13 18:59:15+05:30,"@AmazonHelp hey guys, I'm waiting on a prime o..."
98269,168012,2017-11-25 01:58:17+05:30,@AmazonHelp \nWhat can i do? If i want to star...
40097,1276237,2017-10-26 22:11:14+05:30,@AmazonHelp Except that’s just the signup link...
364035,947211,2017-11-25 22:09:13+05:30,@AmazonHelp when I order off of https://t.co/h...
71430,1480426,2017-11-03 12:56:17+05:30,"Hey @AmazonHelp ,vous avez une erreur de prix...."
352332,862468,2017-10-13 20:10:43+05:30,Bloomin Amazon. You stay in all day waiting fo...
174440,2425938,2017-11-15 01:02:22+05:30,@116928 contrato Amazon Prime para que mi pedi...
277913,397889,2017-11-09 23:42:36+05:30,@Tesco PS4
129447,207619,2017-11-04 02:43:28+05:30,@AmazonHelp El especial The Classics of Hans Z...
233015,2853647,2017-11-28 01:49:33+05:30,@AmazonHelp I’m trying to make a purchase onli...
200248,2616449,2017-11-17 19:45:39+05:30,@120533 @23295 si il faut 10 min pour se conne...
51453,1350259,2017-10-28 00:28:37+05:30,"@AmazonHelp Acaba de llegar. Nunca cambies, Tí..."
143562,222893,2017-10-06 08:31:29+05:30,"@AmazonHelp Once again, Im on the phone w @115..."
75634,150527,2017-11-25 00:34:24+05:30,@115825 Ich wünsche euch noch ein schönen und ...
182710,248657,2017-10-05 21:57:10+05:30,So here's @115821's policy: they will tell you...
236500,2876295,2017-11-28 11:22:27+05:30,アマゾンプライム会員になったぞ〜👏💓AmazonDashButtonひとつくらい欲しいな
81552,1554858,2017-11-05 17:24:52+05:30,@126705 @115830 @AmazonHelp ...during a rough ...
197696,2602303,2017-11-17 13:44:01+05:30,@116439 or @126972 The YT app doesn't allow me...
76832,1515279,2017-11-04 07:16:04+05:30,@AmazonHelp I'm not exactly sure where I shoul...
195670,2588296,2017-10-31 01:43:40+05:30,@AmazonHelp is there a direct line or email I ...
294349,478498,2017-12-01 18:32:24+05:30,@AmazonHelp All thanks and appreciation to you...
13599,1104332,2017-10-15 13:31:05+05:30,"Stop wasting cardboards, improve your packagin..."
40258,1277441,2017-10-17 09:51:17+05:30,@AmazonHelp Try your best before coming to con...
238626,2884883,2017-11-28 17:02:47+05:30,@116935 can I somehow configure the echo dot o...
91892,1626307,2017-11-05 23:57:56+05:30,Reallllly getting annoyed with the fact that @...

In [6]:
random_state=42

In [7]:
import duckdb

con = duckdb.connect()

support_accounts_in_amazon = con.execute("""
    SELECT
        author_id AS support_account,
        COUNT(*) AS message_count
    FROM read_parquet(
        '../data/processed/amazon_conversations.parquet'
    )
    WHERE role = 'support'
    GROUP BY author_id
    ORDER BY message_count DESC
""").df()

support_accounts_in_amazon

   support_account  message_count
0       AmazonHelp         169714
1          UPSHelp            322
2            Tesco            172
3      XboxSupport             14
4     hulu_support             11
5     SpotifyCares             10
6          JetBlue              9
7     ChaseSupport              8
8        BofA_Help              8
9          AskeBay              7
10    AppleSupport              6
11       AskPayPal              6
12      AskSeagate              5
13    ArgosHelpers              5
14       Morrisons              4
15      idea_cares              2
16  AskPlayStation              2
17  MicrosoftHelps              2
18    AsurionCares              2
19       DellCares              2
20         AskAmex              2
21       AskTarget              1
22          AldiUK              1
23    Ask_Spectrum              1
24    Uber_Support              1
25     TMobileHelp              1

In [8]:
contaminated_conversations = con.execute("""
    SELECT
        conversation_id,
        COUNT(*) AS non_amazon_support_messages
    FROM read_parquet(
        '../data/processed/amazon_conversations.parquet'
    )
    WHERE role = 'support'
      AND author_id != 'AmazonHelp'
    GROUP BY conversation_id
    ORDER BY non_amazon_support_messages DESC
""").df()

print("Contaminated conversations:",
      len(contaminated_conversations))

contaminated_conversations.head(20)

Contaminated conversations: 310

   conversation_id  non_amazon_support_messages
0           397889                          167
1           438763                           16
2           463360                           12
3           888183                            9
4           191780                            9
5          1363832                            5
6          1127350                            5
7          1741720                            5
8          2197672                            4
9          1863309                            4
10         1654211                            4
11         1844400                            4
12          606789                            4
13         1634655                            4
14         1788957                            4
15         1306780                            3
16         2834151                            3
17         1464587                            3
18         2454264                            3
19           74438                            3

In [9]:
clean_amazon = con.execute("""
    WITH contaminated AS (
        SELECT DISTINCT conversation_id
        FROM read_parquet(
            '../data/processed/amazon_conversations.parquet'
        )
        WHERE role = 'support'
          AND author_id != 'AmazonHelp'
    )

    SELECT *
    FROM read_parquet(
        '../data/processed/amazon_conversations.parquet'
    )
    WHERE conversation_id NOT IN (
        SELECT conversation_id
        FROM contaminated
    )
""").df()

print("Clean shape:", clean_amazon.shape)

print(
    clean_amazon["role"].value_counts()
)

print(
    "Conversations:",
    clean_amazon["conversation_id"].nunique()
)

Clean shape: (370687, 7)
role
customer    201572
support     169115
Name: count, dtype: int64
Conversations: 82246

In [10]:
import duckdb

con = duckdb.connect()

conversation_397889 = con.execute("""
    SELECT
        conversation_id,
        depth,
        tweet_id,
        author_id,
        role,
        created_at,
        text
    FROM read_parquet(
        '../data/processed/amazon_conversations.parquet'
    )
    WHERE conversation_id = '397889'
    ORDER BY created_at
""").df()

conversation_397889.shape

(425, 7)

In [11]:
conversation_397889["author_id"].value_counts().head(20)

author_id
Tesco     167
525697     17
531486      9
525708      7
524415      6
374104      4
512760      4
522483      4
626265      4
479023      3
366324      3
150460      3
524199      3
482307      3
639922      3
210210      3
525700      3
525710      3
481057      2
482788      2
Name: count, dtype: int64

In [12]:
conversation_397889[
    ["created_at", "author_id", "role", "text"]
].head(20)

,created_at,author_id,role,text
0,2017-11-02 23:11:07+05:30,Tesco,support,The definitive WWII campaign at an unbeatable ...
1,2017-11-04 12:57:57+05:30,479023,customer,@Tesco £43.51 ;)
2,2017-11-04 12:58:43+05:30,Tesco,support,"@479023 Good morning RJ, is there anything I c..."
3,2017-11-04 12:59:05+05:30,479023,customer,@Tesco No thank you.
4,2017-11-04 13:01:25+05:30,Tesco,support,"@479023 Okay no probs, have a good weekend. :)..."
5,2017-11-04 13:07:37+05:30,479024,customer,@Tesco @479023 Sexy you Lara
6,2017-11-04 15:00:20+05:30,593315,customer,@Tesco Paying the money to just look at a load...
7,2017-11-04 15:17:52+05:30,481057,customer,@Tesco I pre-ordered it and payed £46
8,2017-11-04 15:40:23+05:30,Tesco,support,"@593315 Hi there, can you give us some details..."
9,2017-11-04 15:44:34+05:30,Tesco,support,@481057 Hi James. Can you elaborate on what yo...
10,2017-11-04 15:57:11+05:30,482788,customer,@Tesco Is it possible to buy it digitally?
11,2017-11-04 16:01:04+05:30,Tesco,support,"@482788 Hi there, how can I help you? What is ..."
12,2017-11-04 16:01:58+05:30,482788,customer,@Tesco #CODWWII is the offer digital or physic...
13,2017-11-04 16:22:58+05:30,Tesco,support,"@482788 Hi, are you referring to the XBOX Live..."
14,2017-11-04 16:23:00+05:30,Tesco,support,"@482788 If so, the offer is only available onl..."
15,2017-11-04 16:43:14+05:30,482578,customer,@Tesco @481057 You are issue
16,2017-11-04 16:55:59+05:30,481057,customer,@Tesco I paid £2 more...two cheeseburgers there 👀
17,2017-11-04 17:00:34+05:30,480908,customer,@Tesco Is it true yer get 3 months xbox live w...
18,2017-11-04 17:28:03+05:30,Tesco,support,"@480908 This is correct Anthony, however the o..."
19,2017-11-04 17:30:56+05:30,Tesco,support,@481057 Sorry James you haven't mentioned what...

In [13]:
conversation_397889[
    ["created_at", "author_id", "role", "text"]
].tail(20)

,created_at,author_id,role,text
405,2017-11-10 14:31:05+05:30,210210,customer,@Tesco So if your suppliers told you to market...
406,2017-11-10 15:48:21+05:30,Tesco,support,@210210 The retailer have given this descripti...
407,2017-11-10 19:03:29+05:30,525697,customer,"@525700 @525699 @Tesco shut the fuck up idiot,..."
408,2017-11-10 20:59:24+05:30,656408,customer,@Tesco How come its £44 but i got charged £48?
409,2017-11-10 23:02:08+05:30,525700,customer,@525697 @525699 @Tesco Nibble nibble 😩😩
410,2017-11-10 23:46:54+05:30,525697,customer,@525700 @525699 @Tesco not even ganna mention ...
411,2017-11-11 00:59:17+05:30,525710,customer,@626265 @Tesco Mate let’s cancel England vs Ge...
412,2017-11-11 01:59:58+05:30,Tesco,support,"@656408 Hi Kieron, can you please DM your full..."
413,2017-11-11 02:59:36+05:30,659560,customer,@Tesco Bought it this evening in store but pay...
414,2017-11-11 04:00:21+05:30,525700,customer,@525697 @525699 @Tesco Getting personal😩😩😩 nib...
415,2017-11-11 04:03:59+05:30,525701,customer,@525697 @525700 @525699 @Tesco Insult me fella...
416,2017-11-11 07:53:02+05:30,639940,customer,@Tesco @639922 It's 48 in Tesco liars
417,2017-11-11 08:28:41+05:30,Tesco,support,"@659560 Hi Abigail, thanks for taking the time..."
418,2017-11-11 09:38:40+05:30,525697,customer,@525701 @525700 @525699 @Tesco deek you man yo...
419,2017-11-11 09:39:47+05:30,525697,customer,@525700 @525699 @Tesco comes into my mentions ...
420,2017-11-11 16:42:19+05:30,626265,customer,@525710 @Tesco Oh God are you still going on. ...
421,2017-11-20 20:13:56+05:30,766086,customer,@Tesco What's going on with this? Has the pric...
422,2017-11-20 21:56:33+05:30,Tesco,support,"@766086 Hi Jack, this game was originally sold..."
423,2017-11-20 22:58:36+05:30,766086,customer,"@Tesco That's alright, I can't complain about ..."
424,2017-11-20 23:15:23+05:30,Tesco,support,@766086 I hope you can get the best deals next...

In [14]:
conversation_397889.groupby(
    ["author_id", "role"]
).size().sort_values(
    ascending=False
)

author_id  role
Tesco      support     167
525697     customer     17
531486     customer      9
525708     customer      7
524415     customer      6
                      ...
496703     customer      1
496477     customer      1
495804     customer      1
494961     customer      1
517128     customer      1
Length: 157, dtype: int64

In [15]:
for conversation_id in ["397889", "438763", "463360"]:
    print("=" * 80)
    print("CONVERSATION:", conversation_id)
    print("=" * 80)

    summary = con.execute(f"""
        SELECT
            author_id,
            role,
            COUNT(*) AS messages
        FROM read_parquet(
            '../data/processed/amazon_conversations.parquet'
        )
        WHERE conversation_id = '{conversation_id}'
        GROUP BY author_id, role
        ORDER BY messages DESC
    """).df()

    print(summary)

================================================================================
CONVERSATION: 397889
================================================================================
    author_id      role  messages
0       Tesco   support       167
1      525697  customer        17
2      531486  customer         9
3      525708  customer         7
4      524415  customer         6
..        ...       ...       ...
152    494961  customer         1
153    486873  customer         1
154    244187  customer         1
155    517128  customer         1
156    516564  customer         1

[157 rows x 3 columns]
================================================================================
CONVERSATION: 438763
================================================================================
     author_id      role  messages
0      UPSHelp   support        16
1       323800  customer         7
2       767260  customer         2
3   AmazonHelp   support         2
4       461516  customer         2
5       591947  customer         2
6       748556  customer         1
7       519958  customer         1
8       303339  customer         1
9       744241  customer         1
10      115817  customer         1
11      151261  customer         1
12      137732  customer         1
13      783124  customer         1
14      219253  customer         1
15      739877  customer         1
16      270505  customer         1
================================================================================
CONVERSATION: 463360
================================================================================
     author_id      role  messages
0      UPSHelp   support        12
1       807143  customer         6
2       129828  customer         4
3       225139  customer         2
4       803660  customer         2
5       800029  customer         2
6       295866  customer         2
7       232701  customer         2
8       231675  customer         1
9       803661  customer         1
10      803662  customer         1
11      115817  customer         1
12      236247  customer         1
13      225140  customer         1
14      803664  customer         1
15      803663  customer         1
16      157841  customer         1
17      803665  customer         1
18  AmazonHelp   support         1
19      765287  customer         1
20      818065  customer         1